### ISSUE TITLE
Where can I found the 3D CAD Data

### ISSUE THREAD

**Issue by Harhu68** [adafruit/Adafruit-5-HDMI-Backpack-PCB#1]
Hello,

I would like to use the 3D CAD data for a mechanical study? IF we have anough space and how to place it in the car. I could not find the data.

**Comment by ladyada** [comment]
look at
https://learn.adafruit.com/portable-5in-monitor-with-hdmi
https://learn.adafruit.com/adafruit-5-800x480-tft-hdmi-monitor-touchscreen-backpack/downloads
